/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountDownTimer: typeof import('./src/components/tomato-card/components/countDownTimer.vue')['default']
    DataPane: typeof import('./src/components/data-pane/data-pane.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    InputNumber: typeof import('./src/components/tomato-card/components/inputNumber.vue')['default']
    TomatoCard: typeof import('./src/components/tomato-card/tomato-card.vue')['default']
  }
}
